export XR_INTERFACES_LEGACY=Gi0/0/0/0:Gi0-0-0-0,Mg0/RP0/CPU0/0:eth0
export XR_SNOOP_V4_INTERFACES=Mg0/RP0/CPU0/0
export XR_SNOOP_V6_INTERFACES=Mg0/RP0/CPU0/0
export XR_SNOOP_V4_DEFAULT_ROUTE_INTERFACES=
export XR_SNOOP_V6_DEFAULT_ROUTE_INTERFACES=
export XR_CHECKSUM_OFFLOAD_COUNTERACT=Mg0/RP0/CPU0/0
